apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: cbci build actions
inputs:
  integration-name:
    description: 'integration name'
    required: false
    default: ''
  url:  # id of input
    description: 'cbci url'
    required: false
    default: ''
  username:  # id of input
    description: 'username'
    required: false
    default: ''
  token:  # id of input
    description: 'token'
    required: false
    default: ''
  job-name:  # id of input
    description: 'job name'
    required: true
    default: ''
  test-type:  # id of input
    description: 'test type'
    default: ''
  test-result-location:  # id of input
    description: 'test result location'
    default: ''
  parameters:  # id of input
    description: 'parameters'
    default: '{}'

outputs:
  cbci_output:
    value: ${{ steps.invoke-cbci-job.outputs.cbci_output_var }}
    description: CBCI Controller env variable output

  
runs:
  using: composite
  steps:
    - id: invoke-cbci-job
      name: invoke-cbci-job
      # uses: docker://020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/cbci-actions:CBP-5902-f7001a1542fdddf5c242e43cf910e42d35563ceb
      uses: docker://020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/cbci-actions:main-b0cafdbdb7b8769bc1f95552ab4eb2dc5612c1d5
      shell: sh
      env:
        CONFIG_JSON: '{"metaInfo":{"integrationName":"${{ inputs.integration-name }}","url":"${{ inputs.url }}","toolType":"CBCI","username":"${{ inputs.username }}","token":"${{ inputs.token }}","jobName":"${{ inputs.job-name }}","testType":"${{ inputs.test-type }}","fileName":"${{ inputs.test-result-location }}","parameters":${{ inputs.parameters }},"commitId":"${{ cloudbees.scm.sha }}"}}'
        RUN_ID: ${{ cloudbees.run_id }}
        JOB_ID: ${{ job.id }}
        STEP_ID: ${{ step.internal.id }}
        DNS_URL: ${{ cloudbees.api.url }}
        JWT_TOKEN: ${{ cloudbees.api.token }}
      run: |
        set -x
        cd /app
        ./cbci_actions_app invoke -b $CONFIG_JSON
