apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: workflow

on:
  push:
    branches:
      - 'main'

jobs:
  cbci-unstable:
    steps:
      - id: jenkins-via-plugin
        name: invoke-jenkins-job
        uses: ./
        with:
          integration-name: "C5Trigger"
          job-name: "unstable"
          parameters: '{"NAME":"CBCI"}'

  # cbci-long-1-hour:
  #   timeout-minutes: 175  
  #   steps:
  #     - id: jenkins-via-plugin
  #       name: invoke-jenkins-job
  #       uses: ./
  #       with:
  #         integration-name: "C5Trigger"
  #         job-name: "trigger1"
  #         parameters: '{"NAME":"CBCI"}'

  
  # cbci-long-4-hour:
  #   timeout-minutes: 175  
  #   steps:
  #     - id: jenkins-via-plugin
  #       name: invoke-jenkins-job
  #       uses: ./
  #       with:
  #         integration-name: "C5Trigger"
  #         job-name: "trigger2"
  #         parameters: '{"NAME":"CBCI"}'

  cbci-schedule:
    timeout-minutes: 175  
    steps:
      - id: jenkins-via-plugin
        name: invoke-jenkins-job
        uses: ./
        with:
          integration-name: "c6Trigger"
          job-name: "test3"

  cbci-failure:
    steps:
      - id: jenkins-via-plugin
        name: invoke-jenkins-job
        uses: ./
        with:
          integration-name: "C5Trigger"
          job-name: "failure"
          parameters: '{"NAME":"CBCI"}'

  cbci-aborted:
    steps:
      - id: jenkins-via-plugin
        name: invoke-jenkins-job
        uses: ./
        with:
          integration-name: "C5Trigger"
          job-name: "aborted"
          parameters: '{"NAME":"CBCI"}'

  cbci-success:
    steps:
      - id: jenkins-via-plugin
        name: invoke-jenkins-job
        uses: ./
        with:
          integration-name: "C5Trigger"
          job-name: "folder-0/param"
          parameters: '{"NAME":"CBCI"}'

  # cbci-unstable-private:
  #   steps:
  #     - id: jenkins-via-plugin
  #       name: invoke-jenkins-job
  #       uses: ./
  #       with:
  #         integration-name: "RosaasTrigger"
  #         job-name: "unstable"
  #         parameters: '{"NAME":"CBCI"}'


  # cbci-aborted-private:
  #   steps:
  #     - id: jenkins-via-plugin
  #       name: invoke-jenkins-job
  #       uses: ./
  #       with:
  #         integration-name: "RosaasTrigger"
  #         job-name: "aborted"
  #         parameters: '{"NAME":"CBCI"}'


  # cbci-failure-private:
  #   steps:
  #     - id: jenkins-via-plugin
  #       name: invoke-jenkins-job
  #       uses: ./
  #       with:
  #         integration-name: "RosaasTrigger"
  #         job-name: "failure"
  #         parameters: '{"NAME":"CBCI"}'


  # cbci-success-private:
  #   steps:
  #     - id: jenkins-via-plugin
  #       name: invoke-jenkins-job
  #       uses: ./
  #       with:
  #         integration-name: "RosaasTrigger"
  #         job-name: "test"
  #         parameters: '{"NAME":"CBCI"}'

  
  cbci-nojob:
    steps:
      - id: jenkins-via-plugin
        name: invoke-jenkins-job
        uses: ./
        with:
          integration-name: "Rosaas"
          job-name: "nojob"
          parameters: '{"NAME":"CBCI"}'

  cbci-failed:
    steps:
      - id: jenkins-via-plugin
        name: invoke-jenkins-job
        uses: ./
        with:
          integration-name: "controllerTest"
          job-name: "nojob"
          parameters: '{"NAME":"CBCI"}'

  cbci-absent:
    steps:
      - id: jenkins-via-plugin
        name: invoke-jenkins-job
        uses: ./
        with:
          integration-name: "C5Trigger"
          job-name: "nojob"
          parameters: '{"NAME":"CBCI"}'

  # trigger-mstest-test-conversion-using-action:
  #   steps:
  #   - name: Trigger cbci test
  #     #uses: cloudbees-io/cbci-run-job@v2
  #     uses: ./
  #     with:
  #       url: ${{ vars.CJOC_URL }}
  #       username: ${{ secrets.CJOC_USERNAME }}
  #       token: ${{ secrets.CJOC_TOKEN }}
  #       job-name : "cbci-test-reports-mstest"
  #       test-type : "MSTEST"
  #       test-result-location : "*.trx"

  # cbci-run-job-without-output:
  #   steps:
  #     - id: cbci-job
  #       name: invoke-cbci-job
  #       #uses: cloudbees-io/cbci-run-job@v2
  #       uses: ./
  #       with:
  #         url: ${{ vars.CJOC_URL }}
  #         username: ${{ secrets.CJOC_USERNAME }}
  #         token: ${{ secrets.CJOC_TOKEN }}
  #         job-name: JenkinsRunActionTestJob
  
  
      
