apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: workflow

on:
  push:
    branches:
      - 'jenkins-private'

jobs:
  cbci-run-job-without-output:
    steps:
      - id: cbci-job
        name: invoke-cbci-job
        uses: ./
        with:
          url: https://gauntlet-3.cloudbees.com/rosaas/
          username: ${{ secrets.CBCI_PRIVATE_USER }}
          token: ${{ secrets.CBCI_PRIVATE_TOKEN }}
          job-name: aborted

