apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: workflow

on:
  push:
    branches:
      - 'jenkins'

jobs:
  jenkins-job-absent:
    timeout-minutes: 175  
    steps:
      - id: jenkins-via-plugin1
        name: invoke-jenkins-job
        uses: ./
        with:
          integration-name: "JenkinsTrigger"
          job-name: "nojob"
          parameters: '{"NAME":"CloudBees"}'

  jenkins-failed-integration: 
    timeout-minutes: 175  
    steps:
      - id: jenkins-via-plugin1
        name: invoke-jenkins-job
        uses: ./
        with:
          integration-name: "JenkinsDemoRecord"
          job-name: "sleep-2"
          parameters: '{"NAME":"CloudBees"}'

  jenkins-success:   
    timeout-minutes: 175  
    steps:
      - id: jenkins-via-plugin1
        name: invoke-jenkins-job
        uses: ./
        with:
          integration-name: "JenkinsTrigger"
          job-name: "param1"
          parameters: '{"NAME":"Jenkins\u0020Actions"}'

  jenkins-success-folder-empty-parameter:   
    timeout-minutes: 175  
    steps:
      - id: jenkins-via-plugin1
        name: invoke-jenkins-job
        uses: ./
        with:
          integration-name: "JenkinsTrigger"
          job-name: "folderTest/paramJob"

  jenkins-success-4-hours:
    timeout-minutes: 175  
    steps:
      - id: jenkins-via-plugin1
        name: invoke-jenkins-job
        uses: ./
        with:
          integration-name: "JenkinsTrigger"
          job-name: "job10"


  jenkins-long-1-hour:
    timeout-minutes: 175  
    steps:
      - id: jenkins-via-plugin1
        name: invoke-jenkins-job
        uses: ./
        with:
          integration-name: "JenkinsTrigger"
          job-name: "job6"

  jenkins-unstable: 
    timeout-minutes: 175   
    steps:
      - id: jenkins-via-plugin1
        name: invoke-jenkins-job
        uses: ./
        with:
          integration-name: "JenkinsTrigger"
          job-name: "unstable"
          parameters: '{"NAME":"Jenkins"}'

  jenkins-failed: 
    timeout-minutes: 175   
    steps:
      - id: jenkins-via-plugin1
        name: invoke-jenkins-job
        uses: ./
        with:
          integration-name: "JenkinsTrigger"
          job-name: "failure"
          parameters: '{"NAME":"Jenkins"}'

  jenkins-aborted:  
    timeout-minutes: 175  
    steps:
      - id: jenkins-via-plugin1
        name: invoke-jenkins-job
        uses: ./
        with:
          integration-name: "JenkinsTrigger"
          job-name: "aborted"
          parameters: '{"NAME":"CloudBees"}'


  jenkins-scheduled:
    timeout-minutes: 175  
    steps:
      - id: jenkins-via-plugin1
        name: invoke-jenkins-job
        uses: ./
        with:
          integration-name: "LocalJenkinsTrigger"
          job-name: "paramJob"
          parameters: '{"NAME":"CloudBees"}'


  jenkins-integration-absent:
    timeout-minutes: 175  
    steps:
      - id: jenkins-via-plugin1
        name: invoke-jenkins-job
        uses: ./
        with:
          integration-name: "LocalCodeTest12"
          job-name: "paramJob"
          parameters: '{"NAME":"CloudBees"}'

  jenkins-non-default-parameter-job:
    timeout-minutes: 175  
    steps:
      - id: jenkins-via-plugin1
        name: invoke-jenkins-job
        uses: ./
        with:
          integration-name: "JenkinsTrigger"
          job-name: "param1"
          parameters: '{"NAME":"CloudBees"}'

  jenkins-non-default-paramater-job-empty:
    timeout-minutes: 175  
    steps:
      - id: jenkins-via-plugin1
        name: invoke-jenkins-job
        uses: ./
        with:
          integration-name: "JenkinsTrigger"
          job-name: "param1"

  jenkins-non-default-invalid-parameter:
    timeout-minutes: 175  
    steps:
      - id: jenkins-via-plugin1
        name: invoke-jenkins-job
        uses: ./
        with:
          integration-name: "JenkinsTrigger"
          job-name: "param1"
          parameters: '{"NAME12":"CloudBees"}'



  trigger-mstest-test-conversion-using-action:
    steps:
    - name: Trigger cbci test
      #uses: cloudbees-io/cbci-run-job@v2
      uses: ./
      with:
        url: https://c2.saas-preprod.beescloud.com/
        username: cloudbees
        token: ND7TD5zU0k9XQRYGRg2N
        job-name : "cbci-test-reports-mstest"
        test-type : "MSTEST"
        test-result-location : "*.trx"

  cbci-run-job-without-output:
    steps:
      - id: cbci-job
        name: invoke-cbci-job
        #uses: cloudbees-io/cbci-run-job@v2
        uses: ./
        with:
          url: https://c2.saas-preprod.beescloud.com/
          username: cloudbees
          token: ND7TD5zU0k9XQRYGRg2N
          job-name: JenkinsRunActionTestJob



  # jenkins-unauthorised:
  #   outputs:
  #     jenkins_output: ${{ steps.jenkins-job.outputs.jenkins_output }}
    
  #   steps:
  #     - id: jenkins-via-plugin1
  #       name: invoke-jenkins-job
  #       uses: ./
  #       with:
  #         integration-name: "LocalTestactions"
  #         job-name: "paramJob1"
  #         parameters: '{"NAME":"CloudBees"}'
