apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: workflow

on:
  push:
    branches:
      - 'jenkins-private'

jobs:
  cbci-run-job-without-output:
    steps:
      - id: cbci-job
        name: invoke-cbci-job
        uses: ./
        with:
          url: https://jenkins.saas-preprod.beescloud.com/
          username: admin
          token: b3iKs6dnzXCU9uM7McBFI8
          job-name: aborted

