name: Hello World Workflow

on:
  push:
    branches:
      - gh-test

jobs:

  deploy:

    runs-on: ubuntu-latest

    needs: [build, test]

    steps:

      - uses: actions/checkout@v3

      - name: Install dependencies

        run: npm install

      - name: Build production bundle

        run: npm run build --prod

      - name: Deploy to server

        run: |

          ssh user@server "mkdir -p /path/to/app && tar -xzf build.tar.gz -C /path/to/app"



